name: creatures_online_client
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  simple_shadow: ^0.3.1
  flame: ^1.8.0
  flame_audio: ^2.0.3
  shared_preferences: ^2.1.0
  package_info_plus: ^3.0.3
  simple_animations: ^5.0.0+3
  dio: ^5.1.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/images/map/
    - assets/images/map/area_bootcamp/
    - assets/images/avatars/
    - assets/images/team/
    - assets/images/dialog/
    - assets/images/mons/amuranther/
    - assets/images/mons/kikflick/
    - assets/images/mons/menza/
    - assets/images/mons/snorky/
    - assets/images/huds/

    - assets/audio/

  fonts:
    - family: Exo2Black
      fonts:
        - asset: assets/fonts/Exo2-Black.otf

    - family: Exo2Bold
      fonts:
        - asset: assets/fonts/Exo2-Bold.otf

    - family: Exo2ExtraBold
      fonts:
        - asset: assets/fonts/Exo2-ExtraBold.otf

    - family: GarudaBold
      fonts:
        - asset: assets/fonts/Garuda-Bold.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21
